version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    insecure-external-code-execution: deny
    vulnerability-alerts: true