site_name: Trident-Java SDK
docs_dir: docs
site_dir: site

theme:
  name: material  
  language: en
  palette:
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      accent: blue-grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue-grey
      accent: blue-grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
    size: 1.2rem      
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

nav:
  - Overview: index.md
  - Quick Start Guide: quickstart/getting-started.md
  - Security:
    - GPG Verification: security/gpg-verification.md
  - KeyPair Management:
    - Key Management: guides/keypair/key-management.md
  - Transactions:
    - Transaction Guide: guides/transactions/transaction-guide.md
    - Transaction Signing: guides/transactions/signing.md
  - Smart Contracts:
    - Overview: guides/smart-contracts/overview.md
    - Application Binary Interface: guides/smart-contracts/abi.md
    - Contract Deployment: guides/smart-contracts/deployment.md
    - Contract Interaction: guides/smart-contracts/interaction.md
  - API Reference:
    - javadoc: './javadoc/org/tron/trident/core/ApiWrapper.html'

extra:
  version:
    provider: mike
    default: latest
  no_cache: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

plugins:
  - search  
  - mike:
      version_selector: true
      canonical_version: latest
      alias_type: redirect

extra_css:
  - stylesheets/extra.css

#online
#site_url: https://tronprotocol.github.io/trident/
#repo_url: https://github.com/tronprotocol/trident
#repo_name: trident


site_url: https://0xbigapple.github.io/trident-docs/
repo_url: https://github.com/0xbigapple/trident-docs
repo_name: trident-docs
