site_name: Trident-Java SDK
docs_dir: docs
site_dir: site

theme:
  name: material  
  language: en
  palette:
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      accent: blue-grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue-grey
      accent: blue-grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
    size: 1.2rem      
  features:
    - navigation.sections     # Keep section grouping
    - navigation.expand      # Expand navigation by default
    - navigation.indexes
    - navigation.top
    - toc.integrate         # Integrate table of contents
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    
nav:
  - Overview: index.md
  - Quick Start Guide: quickstart/getting-started.md
  - Security:
    - GPG Verification: security/gpg-verification.md
  - KeyPair Management:
    - Key Management: guides/keypair/key-management.md
  - Transactions:
    - Transaction Guide: guides/transactions/transaction-guide.md
    - Transaction Types: guides/transactions/transaction-types.md
    - Transaction Signing: guides/transactions/signing.md
  - Smart Contracts:
    - Overview: guides/smart-contracts/overview.md
    - Application Binary Interface: guides/smart-contracts/abi.md
    - Contract Deployment: guides/smart-contracts/deployment.md
    - Contract Interaction: guides/smart-contracts/interaction.md
  - API Reference:
    - javadoc: ../javadoc/org/tron/trident/core/ApiWrapper.html

extra:
  version:
    provider: mike
    default: 0.9.2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

plugins:
  - search  
  - mike:
      version_selector: true
      canonical_version: 0.9.2 
# Extra directories to include
extra_files:
  - ../javadoc/ 

extra_css:
  - stylesheets/extra.css

site_url: https://0xbigapple.github.io/trident-docs/
repo_url: https://github.com/0xbigapple/trident-docs
repo_name: trident-docs
