name: Dependency Submission

on:
  push:
    branches: [ "main", "release_**" ]    # Trigger on main and release branches
    paths:
      - '**/*.gradle'                     # Watch for gradle build file changes
      - 'gradle.properties'               # Watch for gradle properties changes
      - 'settings.gradle'                 # Watch for settings file changes
  workflow_dispatch:                      # Allow manual trigger

permissions:
  contents: write                         # Grant permission to write dependency graph
  security-events: write                  # Permission for security events

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources           # Checkout repository code
        uses: actions/checkout@v4
        
      - name: Setup Java                 # Setup Java environment
        uses: actions/setup-java@v4
        with:
          java-version: '8'              # Use Java 8
          distribution: 'adopt'           # Change to AdoptOpenJDK
          
      - name: Generate dependency list
        run: |
          ./gradlew :utils:dependencies :abi:dependencies :core:dependencies --configuration runtimeClasspath > dependencies.txt
          
      - name: Parse and submit dependencies
        run: |
          DEPS_JSON=$(cat <<EOF
          {
            "version": 1,
            "detector": {
              "name": "gradle-custom",
              "version": "1.0",
              "url": "https://github.com/${{ github.repository }}"
            },
            "ref": "${{ github.ref }}",
            "sha": "${{ github.sha }}",
            "job": {
              "id": "dependency-graph",
              "correlator": "${{ github.run_id }}"
            },
            "scanned": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "manifests": {
              "build.gradle": {
                "name": "build.gradle",
                "resolved": {
                  "org.springframework:spring-webmvc-portlet": {
                    "package_url": "pkg:maven/org.springframework/spring-webmvc-portlet@4.3.21.RELEASE",
                    "relationship": "direct",
                    "scope": "runtime"
                  }
                }
              }
            }
          }
          EOF
          )
          
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/${{ github.repository }}/dependency-graph/snapshots \
            -d "$DEPS_JSON"