name: Dependency Submission

on:
  push:
    branches: [ "main", "release_**" ]
    paths:
      - '**/*.gradle'
      - 'gradle.properties'
      - 'settings.gradle'
  workflow_dispatch:

permissions:
  contents: write
  security-events: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - uses: mikepenz/gradle-dependency-submission@v0.9.1
        with:
          gradle-project-path: .
          gradle-build-module: |-
            :
            :utils
            :abi
            :core