name: Dependency Monitor

on:
  schedule:
    - cron: '*/40 * * * *'    # Check every 40 minutes
  workflow_dispatch:        # Manual trigger

permissions:
  contents: read
  security-events: read

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check Dependency Graph Status
        id: graph
        run: |
          echo "=== Dependency Graph Check at $(date) ==="
          LAST_UPDATE=$(curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/dependency-graph/snapshots" | jq -r '.updated_at')
          echo "Last dependency graph update: $LAST_UPDATE"
            
      - name: Check Dependabot Status
        id: dependabot
        run: |
          echo "=== Dependabot Status Check at $(date) ==="
          ALERTS=$(curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/dependabot/alerts")
          
          echo "Active Alerts: $(echo $ALERTS | jq '. | length')"
          echo "Latest Alerts:"
          echo $ALERTS | jq -r '.[] | "- \(.security_advisory.summary) (\(.created_at))"' | head -n 5 