name: Dependency Submission

on:
  push:
    branches: [ "main", "release_**" ]    # Trigger on main and release branches
    paths:
      - '**/*.gradle'                     # Watch for gradle build file changes
      - 'gradle.properties'               # Watch for gradle properties changes
      - 'settings.gradle'                 # Watch for settings file changes
  workflow_dispatch:                      # Allow manual trigger

permissions:
  contents: write                         # Grant permission to write dependency graph
  security-events: write                  # Permission for security events

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources           # Checkout repository code
        uses: actions/checkout@v4
        
      - name: Setup Java                 # Setup Java environment
        uses: actions/setup-java@v4
        with:
          java-version: '8'              # Use Java 8
          distribution: 'adopt'           # Change to AdoptOpenJDK
          
      - name: Generate and submit dependency graph    # Generate and submit dependency graph
        uses: gradle/gradle-build-action@v2          # Use correct action path
        with:
          dependency-graph: generate-and-submit
          arguments: :utils:dependencies :abi:dependencies :core:dependencies --configuration runtimeClasspath --scan