name: Deploy Trident Documentation
run-name: Deploy Version ${{ inputs.version }}
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g. 0.9.2)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: md-docs

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mike

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"    

      - name: Deploy docs
        run: |

          mike delete --push ${{ github.event.inputs.version }} || true
          
          mike deploy --push --update-aliases ${{ github.event.inputs.version }} latest
          mike set-default --push latest
          
          mkdocs build --clean --site-dir site
          
          mike list 